apiVersion: v1
kind: ConfigMap
metadata:
  name: test-demo
data:
  database.properties: |-
    {{$.Files.Get "files/database.properties"| nindent 4}}
  application.properties: |-
    {{$.Files.Get "files/application.properties"| nindent 4}}